[package]
name = "todo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.26"
strum = { version = "0.24", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }